###
POST http://localhost:5000/api/jenispengaduan
Content-Type: application/json

{
  "jenisPengaduan":"Penertiban Parkir Liar"
}

###
get http://localhost:5000/api/jenispengaduan

###
POST http://localhost:5000/api/pengguna/register
Content-Type: application/json

{
    "name":"Iqbal Manazil Yuni",
    "username":"Accismus",
    "password":"admin12345",
    "nomor_hp":"081234324433",
    "role":"super admin",
    "addres":"Jln Moh.Hatta No 1 Pasar Ambacang"
}

###
POST http://localhost:5000/api/kabupatenkota
Content-Type: application/json

{
  "kabupatenkota":"Kota Padang"
}